# ===================================
# Filter Scope Definitions
# ===================================

scopes:

    js:
        label: JavaScript
        type: checkbox
        conditions: language = 1

    php:
        label: PHP
        type: checkbox
        conditions: language = 2

    css:
        label: CSS
        type: checkbox
        conditions: language = 3
