# ===================================
#  Form Behavior Config
# ===================================

name: indikator.plugins::lang.plugin.title
form: ~/plugins/indikator/plugins/models/frontend/fields.yaml

modelClass: Indikator\Plugins\Models\Frontend
defaultRedirect: indikator/plugins/frontend

create:
    redirect: indikator/plugins/frontend/update/:id
    redirectClose: indikator/plugins/frontend

update:
    redirect: indikator/plugins/frontend/update/:id
    redirectClose: indikator/plugins/frontend
